### ISSUE TITLE
tweak repository name

### ISSUE THREAD

**Issue by davidchambers** [hemanth/functional-programming-jargon#10]
"Jargon" is a mass noun, so the trailing "s" should be dropped (unless "jargons" is a reference to a meme with which I'm unfamiliar).

**Comment by hemanth** [comment]
Makes absolute sense!

**Comment by raine** [comment]
:+1:

**Comment by hemanth** [comment]
Done, thanks!

**Comment by raine** [comment]
The word "jargons" still appears in the repo description and readme.

**Comment by hemanth** [comment]
thanks, fixed it [here](https://github.com/hemanth/functional-programming-jargon/commit/12177e6f9da66d935b0385e140f767ad8099039d)

**Comment by stoeffel** [comment]
Still one left in the repo description.

<img width="695" alt="screen shot 2015-09-21 at 09 02 30" src="https://cloud.githubusercontent.com/assets/1217681/9986655/93279074-603f-11e5-80fe-33aea47ff68e.png">

**Comment by hemanth** [comment]
:dash:
